[package]
name = "fever"
version = "0.1.0"
edition = "2021"
authors = ["ltoddy <taoliu0509@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "setup the on-line manual pages"

[build-dependencies]
manman = "0.1.2"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
git2 = "0.13"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
tinytemplate = "1.2"
